### PR TITLE
updating nworkscore to 1 instead of 0

### PR DESCRIPTION
**Pull request by ghabs**
small update PR, fixing https://github.com/drivechain-project/bitcoin/issues/22

Tests pass, PTAL and verify that the tests still match the intended business logic

### CODE REVIEW

**Comment by ghabs** [comment]
Is this change to work scores still needed, if not I'll close this PR.

**Comment by CryptAxe** [comment]
@ghabs Still needed, and very much appreciated. I have been too busy to really audit this too my satisfaction (and it's a pretty important change) so I'm sorry you haven't heard anything. It looks good to me, requires a rebase now though... (sorry)

Do you mind if I just open a PR into your branch to rebase this and then we can merge it in?

**Comment by ghabs** [comment]
No problem! And sure feel free to open the PR into the branch

**Comment by CryptAxe** [comment]
@ghabs once the rebase PR is merged into your branch, we can merge this.

**Review by CryptAxe — APPROVED** [review]

**Pull request merged**
